name: linter

on:
  workflow_call:

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Wayfinder Routes
        run: php artisan wayfinder:generate --with-form

      - name: Run Pint
        run: composer lint

      - name: Run Rector
        run: composer rector

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: fix code style
          commit_options: '--no-verify'
